# Generated by Django 5.2.7 on 2025-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_bookcomment_borrowrequest_borrowrequestitem_loan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("RETURNED", "Returned"),
                    ("LOST", "Lost"),
                    ("OVERDUE", "Overdue"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
