# Generated by Django 5.2.7 on 2025-11-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_borrowrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowrequest",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="borrowrequest",
            name="rejection_reason",
        ),
    ]
