# Generated by Django 5.2.7 on 2025-11-28 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_borrowrequest_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (7, "1 Week"),
                    (14, "2 Weeks"),
                    (30, "1 Month"),
                    (90, "3 Months"),
                    (180, "6 Months"),
                ],
                default=7,
            ),
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="requested_from",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="requested_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
